### PR TITLE
Add logos for pendulum and amplitude

### PR DESCRIPTION
**Pull request by gianfra-t**
## I already know, confirm and agree
- [ ] [The disclaimer](https://github.com/zenlinkpro/assets#disclaimer)

Part of [Tasks/194](https://github.com/pendulum-chain/tasks/issues/194). This PR just adds the GLMR asset logo which is Moonbeam.
Also, as part of [Tasks/211](https://github.com/pendulum-chain/tasks/issues/211) we also add the icons for 3 new assets.

### CODE REVIEW

**Comment by ebma** [comment]
For simplicity, let's also add the icons for Amplitude (USDC, USDT, and XLM) required by [this](https://github.com/pendulum-chain/tasks/issues/211).

**Comment by gianfra-t** [comment]
@pendulum-chain/devs this is just an internal review PR, if you think this is fine I will point this to the upstream repo and open the actual pr for zenlink.

**Review by ebma — APPROVED** [review]
Looks good 👍

**Comment by gianfra-t** [comment]
Closing this as the [PR](https://github.com/zenlinkpro/assets/pull/72) to the upstream repo has been created.

**Pull request closed without merging**
